### ISSUE TITLE
Error on VS Code

### ISSUE THREAD

**Issue by EpsilonKu** [acherkashin/yandex-music-extension#10]
![Screenshot from 2020-09-15 16-35-33](https://user-images.githubusercontent.com/63652620/93200690-ef841f80-f771-11ea-9fbe-7a6313119ca3.png)

I wrote login and password correctly. But I got this error. 
OS: Elementary OS 5.1.4 (Ubuntu 18.04).
VS Code installed by deb package.

**Comment by acherkashin** [comment]
@EpsilonKu The problem that I package this extension from windows machine and thus execution files for windows and for linux are not included. It seems, I am not only one who faced with this issue, the same problem has been described [here](https://discuss.atom.io/t/packaging-for-vscode-extension/61406). I will try to fix it as soon as I get time, any help is appreciated.

**Comment by acherkashin** [comment]
@EpsilonKu 

[Here is the new cross-platform](https://drive.google.com/file/d/1kmmUHE_fdJRk1iQCswh4tkp3P6j--riD/view?usp=share_link) version of the extension I'm working in [this merge request](https://github.com/acherkashin/yandex-music-extension/pull/72).

I would appreciate if you could try to install it and let me know which OS you used 🙏

**Comment by acherkashin** [comment]
It does work!

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/9947582/205233389-a06c43c8-1edb-47af-b84a-70695e4cc1b2.png">

**Comment by EpsilonKu** [comment]
Ohh my God!!! Sorry for late reply. Tomorrow I will check.

**Comment by EpsilonKu** [comment]
Works perfectly.

**Comment by acherkashin** [comment]
@EpsilonKu 

Cool! Thanks for testing, I will publish the new version soon to the store.

**Comment by acherkashin** [comment]
Fixed in #72. Need to upgrade extension to 0.11 version.
