### ISSUE TITLE
Не логинит

### ISSUE THREAD

**Issue by lyaguxafrog** [acherkashin/yandex-music-extension#100]
Не могу залогиниться в аккаунт, ввожу почту пароль:
![image](https://github.com/acherkashin/yandex-music-extension/assets/36086205/8a0a23dd-d62c-4380-9407-b6f548b41e6f)
Яндекс пишет на почту, что в аккаунт зашел

использую генератор одноразовых паролей( по типу гугл аунтификатор )

**Comment by acherkashin** [comment]
@lyaguxafrog Можете попробовать зайти с помощью токена? Яндекс ограничивает доступ по логину и паролю, думаю в этом дело.

**Comment by acherkashin** [comment]
Думаю нужно добавить рекоммендацию для входа по токену в сообщение с ошибкой.

**Comment by lyaguxafrog** [comment]
> @lyaguxafrog Можете попробовать зайти с помощью токена? Яндекс ограничивает доступ по логину и паролю, думаю в этом дело.

получилось, но все таки по логину удобнее

**Comment by acherkashin** [comment]
@lyaguxafrog Согласен, но к сожалению яндекс режет возможность входа по логину и паролю
