### ISSUE TITLE
Пропала возможность авторизации

### ISSUE THREAD

**Issue by KOTOKOPOlb** [acherkashin/yandex-music-extension#101]
Установил, вошёл в аккаунт и всё работало. Сейчас перенёс жесткий диск с одного пк на другой и все расширения слетели, скачал, а кнопки авторизации нету.
![image](https://github.com/acherkashin/yandex-music-extension/assets/82699565/1b2afb00-d92d-452c-8c71-0d44d398c5f8)

**Comment by acherkashin** [comment]
@KOTOKOPOlb Попробуйте выйти и войти

<img width="379" alt="image" src="https://github.com/acherkashin/yandex-music-extension/assets/9947582/025394b4-3160-4c56-9cb5-6b911545fd17">

**Comment by KOTOKOPOlb** [comment]
@acherkashin нету кнопки
![image](https://github.com/acherkashin/yandex-music-extension/assets/82699565/d166f188-50fa-4924-bc13-8391b4969ed4)

**Comment by acherkashin** [comment]
@KOTOKOPOlb Нужно ввести знак больше а затем "yandex music: выйти", как у меня на скрине

**Comment by KOTOKOPOlb** [comment]
@acherkashin Ввёл и кнопки появились, я пошёл за токеном и кнопки снова пропали.
Теперь при заходе в vs code кнопки есть, но они почти сразу пропадают

**Comment by KOTOKOPOlb** [comment]
Успел авторизоваться до пропадания кнопок, сейчас вроде работает
