### ISSUE TITLE
"Большая перемотка" collection has wrong icon

### ISSUE THREAD

**Issue by acherkashin** [acherkashin/yandex-music-extension#11]
![image](https://user-images.githubusercontent.com/9947582/93864423-8a7a7d80-fccd-11ea-81e7-dff7c64f50cf.png)

**Comment by AlexSnowLeo** [comment]
Hey @acherkashin. I've some note only. This is a temporary playlist, was added for the 10th anniversary of the music service, and it no longer appears in the top lists. I do not think that it is necessary to make a separate icon for it.

**Comment by acherkashin** [comment]
@AlexSnowLeo 

I think, we don't need to embed these icons in code. We need to request them via API.

**Comment by acherkashin** [comment]
@AlexSnowLeo you can use `vscode.Uri.parse` function to request icon and use it for `TreeItem`.
To get correct icon uri, you need to use `getCoverUri` function. So, solution is:

```ts
const item = new vscode.TreeItem(...);
item.iconPath = vscode.Uri.parse(getConverUri(track.coverUri, 50));
```

**Comment by AlexSnowLeo** [comment]
https://github.com/acherkashin/yandex-music-extension/pull/23
