### ISSUE TITLE
Enhance password storing reliability

### ISSUE THREAD

**Issue by acherkashin** [acherkashin/yandex-music-extension#17]
Currently credentials are stored in `settings.json` file which is completely unsecure. 

Need to use whether [`node-keytar`](https://github.com/atom/node-keytar) library or native [vscode wrapper](https://github.com/microsoft/vscode/blob/master/src/vs/vscode.proposed.d.ts#L102) around this library when it will be stable.

**Comment by MarshalX** [comment]
Why are you using credentials instead of a token?

**Comment by acherkashin** [comment]
@MarshalX It is good question, I think I need to store credentials as you've suggested and store it in [SecretStorage](https://code.visualstudio.com/api/references/vscode-api#SecretStorage)
