### ISSUE TITLE
логинит, показывает список треков, но не играет

### ISSUE THREAD

**Issue by tst32** [acherkashin/yandex-music-extension#43]
{"code":"ERR_IPC_CHANNEL_CLOSED"} и uid Cannot read property 'uid' of undefined
а слева треки показывает, кнопка скачать работает (облако) открывает браузер на треке.

**Comment by acherkashin** [comment]
@tst32 Подскажите на какой операционной системе используете VS Code?

**Comment by tst32** [comment]
ubuntu 20.04.
```
Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:39:46.686Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.4.0-96-generic
```
еще при логине я использую одноразовый пароль из Я.Ключ может в этом дело?

**Comment by acherkashin** [comment]
Нет, всё дело в убунте, сейчас поддерживается только винда, потому что для проигрывания музыки используется электрон. Когда упаковывается расширение, то публикуются только виндовые файлы, из-за того, что я работаю под виндой. Для линукса сделал [отдельную версию](https://github.com/acherkashin/yandex-music-extension/releases/download/0.10.0/ubuntu-yandex-music-extension-0.10.0.vsix). Она должна работать.

**Comment by acherkashin** [comment]
@tst32 отпишитесь, если проверили билд для линукса

**Comment by tst32** [comment]
💯 Работает

**Comment by ilyakuchaev** [comment]
Может и для Mac соберете? )

**Comment by acherkashin** [comment]
@ilyakuchaev Я хочу, но времени все нет. Под мак нельзя просто собрать как под винду или Линукс. Нужно устанавливать electron в рантайме, как это делает Microsoft Life Share.

**Comment by acherkashin** [comment]
Наткнулся на пакет [@electron/get](https://github.com/electron/get), который решает эту проблему. @ilyakuchaev Не хочешь попробовать реализовать? 😉

**Comment by acherkashin** [comment]
@ilyakuchaev Работаю [вот тут](https://github.com/acherkashin/yandex-music-extension/pull/72) над новой версией. Хочу добавить поддержку линукса и мака из коробки. Вот [тут можно скачать новую версию](https://drive.google.com/file/d/1kmmUHE_fdJRk1iQCswh4tkp3P6j--riD/view?usp=share_link), буду благодарен за тестирование.

@tst32 Есть возможность протестировать на линуксе? 🙏

**Comment by acherkashin** [comment]
It does work!

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/9947582/205233389-a06c43c8-1edb-47af-b84a-70695e4cc1b2.png">

**Comment by acherkashin** [comment]
Fixed in !72. Need to upgrade extension to 0.11 version.

**Comment by ilyakuchaev** [comment]
> Наткнулся на пакет [@electron/get](https://github.com/electron/get), который решает эту проблему. @ilyakuchaev Не хочешь попробовать реализовать? 😉

Я могу только потестировать )
Я больше Опс, чем Дев )

**Comment by acherkashin** [comment]
@ilyakuchaev Тогда пора тестировать, выпустил новую версию. Заранее спасибо и дайте знать, если проблема решилась.
