### ISSUE TITLE
Проблема с расширением на ubuntu 22.10

### ISSUE THREAD

**Issue by mmrkvkn** [acherkashin/yandex-music-extension#81]
Расширение не работает на версии 0.12. Не может найти файлы модуля.
Откатился на версию 0.11.2, всё работает, но там не открывается плейлист 'мне нравится'.
![image](https://user-images.githubusercontent.com/97022342/218267286-d9daeaa1-357f-46c8-9e6a-8807bacb4286.png)
![image](https://user-images.githubusercontent.com/97022342/218267361-30c871e2-6f68-4f89-993c-7d88b9f08f7a.png)

**Comment by acherkashin** [comment]
@mmrkvkn странно, выкатил версию 0.13, можешь проверить она тоже не работает?

**Comment by acherkashin** [comment]
@mmrkvkn на убунте теперь всё должно работать
