### ISSUE TITLE
Ошибка проигрывания без авторизации

### ISSUE THREAD

**Issue by bbird1980** [acherkashin/yandex-music-extension#89]
Без авторизации проигрывание трека не работает и никаких ошибок не пишет, просто в статусе проигрывания, но звука нет. Мак, вскод последний. Клик на новые релизы выдает тост с ошибкой bad request — это ожидаемое без авторизации, а проигрывание публичного чарта — не ясно что происходит, по идее должно работать.
<img width="372" alt="image" src="https://user-images.githubusercontent.com/12080370/229348937-44099071-cfd5-40d0-bce9-c7ec50d7becb.png">

**Comment by bbird1980** [comment]
А, ну и также проблема: вход по токену, указал токен, нажал Enter и ничего не происходит, ни ошибок, ничего

**Comment by bbird1980** [comment]
Версия: 1.77.0 (Universal)
Фиксация: 7f329fe6c66b0f86ae1574c2911b681ad5a45d63
Дата: 2023-03-29T09:57:11.797Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.4.0
Изолированные: Yes

**Comment by acherkashin** [comment]
Перевроверю, @bbird1980 а если перезагрузить расширение?

**Comment by bbird1980** [comment]
Не помогло, только после ввода токена и ничего в ответ теперь пропали чарты и поиск не работает. Включал электрон, но там пусто, ничего полезного вроде.

**Comment by acherkashin** [comment]
Странно, я только проверил у меня работает вход по токену. Добавлю логов в новой версии

**Comment by acherkashin** [comment]
@bbird1980 ты берёшь токен в [Google Chrome Extension](https://chrome.google.com/webstore/detail/yandex-music-token/lcbjeookjibfhjjopieifgjnhlegmkib)?

**Comment by bbird1980** [comment]
Ну я не стал авторизовывать непонятное приложение своим акком и создал свое тестовое приложение с максимальным скоупом и получил свой токен и авторизовал.

**Comment by acherkashin** [comment]
Авторизовываться нужно именно токеном яндекс музыки. Создать приложение для Я.Музыки нельзя. Похоже токен неверный.
