### ISSUE TITLE
Ошибка во время авторизации при наличии загруженных треков в "Мне нравится"

### ISSUE THREAD

**Issue by shemanaev** [acherkashin/yandex-music-extension#90]
После авторизации экстеншн запрашивает список лайков, в котором присутствуют загруженные треки и ему от этого плохеет.
`id` в виде uuid и без `albumId` превращается в `trackId` с `undefined`.

Ответ с лайками
![изображение](https://user-images.githubusercontent.com/1058537/229371231-13095be8-f135-4d92-be1a-4529bcf57eaa.png)

Запрос треков
![изображение](https://user-images.githubusercontent.com/1058537/229371299-3afbc8b1-bf16-4c52-ac0a-6342161d0317.png)

Проверка на наличие `albumId` в https://github.com/acherkashin/yandex-music-extension/blob/99542c74d9888bee91785dc4f40943969527eac6/src/YandexMusicApi/ApiUtils.ts#L11

```js
return track.albumId ? `${track.id}:${track.albumId}` : track.id;
```

помогает, но API не находит такие треки
![изображение](https://user-images.githubusercontent.com/1058537/229374549-9ddb9120-8995-4231-b5a3-eab90115a90d.png)

Самое интересное, что веб версия запрашивает через https://music.yandex.ru/handlers/track-entries.jsx трек по `id` такого же формата и получает его.

**Comment by acherkashin** [comment]
@shemanaev Ошибка исправлена в последней версии (0.15.4)

https://github.com/acherkashin/yandex-music-extension/commit/e469773d9cca6b42d7459b8a0821e83d806e0acc
