### ISSUE TITLE
не работает на линуксе

### ISSUE THREAD

**Issue by lllzebralll** [acherkashin/yandex-music-extension#93]
![image](https://user-images.githubusercontent.com/58988816/230003359-8ec97c6d-91af-41fc-afb3-c5892c18f0ee.png)
![image](https://user-images.githubusercontent.com/58988816/230003461-7a0cb758-cb6d-4cf7-a412-057677c1e44b.png)
![image](https://user-images.githubusercontent.com/58988816/230003521-521035c0-d74c-4174-bf14-42248843ef19.png)
![image](https://user-images.githubusercontent.com/58988816/230003628-27bff793-8462-4b0f-badd-fa82a772e073.png)

**Comment by Katze-942** [comment]
Подтверждаю, Endeavour OS
![image](https://user-images.githubusercontent.com/48821354/230096333-ee5846b7-b82f-4c60-b3dc-0f9f7c01eb01.png)

**Comment by acherkashin** [comment]
@lllzebralll @Katze-942 подскажите, какая версия Ubuntu?

**Comment by lllzebralll** [comment]
PopOS 22.04 LTS

**Comment by lllzebralll** [comment]
у Katze  arch симейство

**Comment by glutaminefree** [comment]
На Fedora 37 такие же симптомы

**Comment by acherkashin** [comment]
@glutaminefree @lllzebralll @Katze-942 выпустил версию 0.15.2 должно всё работать, можете проверить?

**Comment by glutaminefree** [comment]
@acherkashin Я уже успел перейти c Fedora на Manjaro. Тут плагин тоже не работал, но теперь всё хорошо работает!
Благодарю за исправления! Отличная идея плагина и исполнение :)
