### ISSUE TITLE
Bad request 

### ISSUE THREAD

**Issue by bropines** [acherkashin/yandex-music-extension#96]
При запуске в обычной винде, под впном/без впна бед реквест
![image](https://github.com/acherkashin/yandex-music-extension/assets/57861007/02d7922d-5908-48fa-8f2a-9a885d4fb730)
```
2023-06-09 21:53:31.190 [error] ApiError: Bad Request
	at new ApiError (c:\Users\bropi\.vscode\extensions\acherkashin.yandex-music-extension-0.15.2\node_modules\yandex-music-client\core\ApiError.js:22:28)
	at catchErrorCodes (c:\Users\bropi\.vscode\extensions\acherkashin.yandex-music-extension-0.15.2\node_modules\yandex-music-client\core\request.js:286:15)
	at c:\Users\bropi\.vscode\extensions\acherkashin.yandex-music-extension-0.15.2\node_modules\yandex-music-client\core\request.js:325:21
	at step (c:\Users\bropi\.vscode\extensions\acherkashin.yandex-music-extension-0.15.2\node_modules\yandex-music-client\core\request.js:44:23)
	at Object.next (c:\Users\bropi\.vscode\extensions\acherkashin.yandex-music-extension-0.15.2\node_modules\yandex-music-client\core\request.js:25:53)
	at fulfilled (c:\Users\bropi\.vscode\extensions\acherkashin.yandex-music-extension-0.15.2\node_modules\yandex-music-client\core\request.js:16:58)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by acherkashin** [comment]
@bropines Подскажите, какой VPN используете и какую страну указываете?

**Comment by bropines** [comment]
> @bropines Подскажите, какой VPN используете и какую страну указываете?

Если через VPN то нидерланды, если без впн то соответственно РФ.

**Comment by acherkashin** [comment]
@bropines А каким VPN сейчас пользуетесь?

**Comment by bropines** [comment]
> @bropines А каким VPN сейчас пользуетесь?

Если вопрос про сервис, то prostovpn.

**Comment by bropines** [comment]
И я снова тут. С тех пор я, сменил винду, сменил ось, сменил впн. Результат? ноль. Бэд реквест -_-

**Comment by acherkashin** [comment]
@bropines А без VPN работает или также Bad Request?

**Comment by bropines** [comment]
> @bropines А без VPN работает или также Bad Request?

Пробовал без впн, с казахским, японским, канадским, германским. Так же пробовал включать/отключать goodbyedpi. Мне что кажется я не правильно получаю ключ или неверно ввожу код от аккаунта...

**Comment by acherkashin** [comment]
Токен проще всего получать с помощью расширения для хрома 
https://chrome.google.com/webstore/detail/yandex-music-token/lcbjeookjibfhjjopieifgjnhlegmkib

Вход по логину и паролю почти не работает, яндекс урезает эту возможность

![image](https://github.com/acherkashin/yandex-music-extension/assets/9947582/5664f19c-01ec-4071-af58-9f20ae1b6fc6)

**Comment by bropines** [comment]
> Токен проще всего получать с помощью расширения для хрома https://chrome.google.com/webstore/detail/yandex-music-token/lcbjeookjibfhjjopieifgjnhlegmkib
> 
> Вход по логину и паролю почти не работает, яндекс урезает эту возможность
> 
> ![image](https://user-images.githubusercontent.com/9947582/282285970-5664f19c-01ec-4071-af58-9f20ae1b6fc6.png)

Может ли такое что косяк в аккаунте?

**Comment by bropines** [comment]
https://github.com/acherkashin/yandex-music-extension/assets/57861007/225abecf-ea6f-4868-914c-faaa2ba00947

**Comment by bropines** [comment]
![image](https://github.com/acherkashin/yandex-music-extension/assets/57861007/ea509c64-d88b-4c58-b9b6-870164aed574)


Если ввести первый токен без y0 то выдаст бэд реквест и этот токен от основного акка.
![image](https://github.com/acherkashin/yandex-music-extension/assets/57861007/b20290f7-26e5-4a76-8a6a-b6b51f53d633)

Если ввести второй токен с y0, то выдаст error и просьбу перепроверить токен, хотя этот токен я получил от расширения
![image](https://github.com/acherkashin/yandex-music-extension/assets/57861007/1ad114e0-7705-4495-ba03-59105f246b11)

**Comment by acherkashin** [comment]
@bropines А вы в России находитесь?

**Comment by bropines** [comment]
> @bropines А вы в России находитесь?

Да. Без впна тоже пробовал. Результат тот же.

**Comment by acherkashin** [comment]
Проблема была в том, что у некоторых треков нет альбома. И в этом случае строился некорректный идентификатор в `createAlbumTrackId` в `ApiUtils.ts`
