### ISSUE TITLE
Поломанная система входа в аккаунт

### ISSUE THREAD

**Issue by igorir3** [acherkashin/yandex-music-extension#97]
При входе по логину: ошибка логина или пароля
При входе по токену: ошибка входа

Короче есть два стула...

**Comment by acherkashin** [comment]
@igorir3 подскажите, как получали токен?

**Comment by igorir3** [comment]
А... Крч качаешь плагин для google chrome, заходишь на сайт yandex.music, и запускаешь плагин через меню расширений. И там будет текст: скопировать токен, нажмите на него и токен будет скопирован в буфер обмена

**Comment by Tabulanga** [comment]
не удается залогиниться с логином/паролем -- причем точно правильно. на почту приходит уведомление о входе

**Comment by acherkashin** [comment]
> не удается залогиниться с логином/паролем -- причем точно правильно. на почту приходит уведомление о входе

Попробуйте войти по токену. С логином/паролем у большинства проблемы.

**Comment by Tabulanga** [comment]
> > не удается залогиниться с логином/паролем -- причем точно правильно. на почту приходит уведомление о входе
> 
> Попробуйте войти по токену. С логином/паролем у большинства проблемы.

нет удобного способа получить этот токен, без плясок с бубном.
да и как-то если есть вариант логина/пароля -- хочется, чтобы он был рабочим

**Comment by acherkashin** [comment]
> > > не удается залогиниться с логином/паролем -- причем точно правильно. на почту приходит уведомление о входе
> > 
> > 
> > Попробуйте войти по токену. С логином/паролем у большинства проблемы.
> 
> нет удобного способа получить этот токен, без плясок с бубном. да и как-то если есть вариант логина/пароля -- хочется, чтобы он был рабочим

Для токена, есть экстеншн - https://chrome.google.com/webstore/detail/yandex-music-token/lcbjeookjibfhjjopieifgjnhlegmkib

> да и как-то если есть вариант логина/пароля -- хочется, чтобы он был рабочим

к сожалению этот способ блочится самим яндексом, тут я ничего поделать не могу(
